### ISSUE TITLE
Prerendering can't be disabled on Netlify

### ISSUE THREAD

**Issue by Gibbu** [roxiness/routify#199]
**Bug description**
Trying to disable prerendering just doesn't seem to work.
Methods I've tried to disable it:
- Added `cross-env PRERENDER=false` to the `package.json/build` script.
- Added `.env` file with `PRERENDER=false` to the root of my project.
- Added `PRERENDER=false` to Netlify.

Completely removing the `prerender` function from the `rollup.config.js` file results in the page just 404'ing. 

**package.json**
```json
{
  "scripts": {
    "build": "cross-env PRERENDER=false npm run routify -- -b && rollup -c"
  },
}
```

**Version**
Svelte: `3.20.1`
Routify: `1.5.9`

**Additional info**
I've currently got the prerender functions enabled because without them enabled the website just 404s

If you wish you can view all my files here: https://github.com/Gibbu/site
Just so you don't have to keep asking what I've got inside said files.

**Comment by jakobrosenberg** [comment]
Set this line to false
https://github.com/Gibbu/site/blob/master/rollup.config.js#L15

The reason the env variable doesn't work is because it doesn't return a boolean value, so it will always be truthy.

**Comment by Gibbu** [comment]
I've just set it to false and now returns a 404

**Comment by jakobrosenberg** [comment]
What address are you trying to visit?

**Comment by Gibbu** [comment]
https://gibbu.me

**Comment by jakobrosenberg** [comment]
Does it work locally with 
```
npm run build
npm run serve
```

**Comment by Gibbu** [comment]
It does indeed.

**Comment by jakobrosenberg** [comment]
It looks like you you don't have url rewrite/redirect enabled on your host. It's enabled in the repo you shared. Is it disabled in your local Netlify config?

**Comment by Gibbu** [comment]
Where would I find this Netlify config?

**Comment by jakobrosenberg** [comment]
/scripts/netlify/api/ssr/ssr.js

**Comment by Gibbu** [comment]
I've not touched this file but it looks like this
```javascript
const fs = require('fs')
const { ssr } = require('@sveltech/ssr')
const { script, template } = require('./bundle.json')

exports.handler = async (event, context) => {
    const body = await ssr(template, script, event.path)
    return { statusCode: 200, body: body + '\n<!--ssr rendered-->' }
}
```

**Comment by jakobrosenberg** [comment]
Sorry, my bad. Meant `/scripts/netlify/netlify.toml`

**Comment by Gibbu** [comment]
```toml
[build]
  publish = "public/"
  functions = "api/"
  ignore = "git diff --quiet HEAD^ HEAD ../../"

[[redirects]]
  # SSR and SPA
  # from = "/*"
  # to = "/.netlify/functions/ssr"
  # status = 200
  
  # SPA only
  from = "/*"
  to = "/__app.html"
  status = 200
```
